package quic

//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/For-ACGN/quic-bbr streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/For-ACGN/quic-bbr cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/For-ACGN/quic-bbr receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/For-ACGN/quic-bbr sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/For-ACGN/quic-bbr streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/For-ACGN/quic-bbr streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_data_handler_test.go github.com/For-ACGN/quic-bbr cryptoDataHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_frame_source_test.go github.com/For-ACGN/quic-bbr frameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_ack_frame_source_test.go github.com/For-ACGN/quic-bbr ackFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/For-ACGN/quic-bbr streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_sealing_manager_test.go github.com/For-ACGN/quic-bbr sealingManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/For-ACGN/quic-bbr unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_packer_test.go github.com/For-ACGN/quic-bbr packer"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/For-ACGN/quic-bbr sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/For-ACGN/quic-bbr quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/For-ACGN/quic-bbr packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/For-ACGN/quic-bbr unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/For-ACGN/quic-bbr packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/For-ACGN/quic-bbr multiplexer"
